logging:
  level:
    .: error
    org.springframework: ERROR
    org.hibernate: ERROR

spring:
  profiles.active: default

---
spring:
  profiles: default

  datasource:
    url: jdbc:mysql://localhost:3306/selfmetrics
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect

#---
#spring:
#  profiles: functional-tests
#
#  datasource:
#    url: jdbc:h2:tcp://${databaseHost}/~/${databaseName};MVCC=true;DB_CLOSE_DELAY=-1;MODE=Oracle;DB_CLOSE_ON_EXIT=FALSE
