logging:
  level:
    .: debug
    org.springframework: ERROR
    org.hibernate: ERROR

spring:
  profiles.active: default

---
spring:
  profiles: default

rethinkdb:
  host: localhost
  name: self_metrics